### PR TITLE
Adds ship

### PR DESCRIPTION
**Pull request by Nickvr628**
Adds Botany Bay ship file. A medium size NT industrial ship.
image

image

image

image

It is missing an engine room and power system since we have not developed the warp core system yet.

### CODE REVIEW

**Comment by nichlas0010** [comment]
>no pictures

**Comment by Nickvr628** [comment]
Travis please

**Comment by Kmc2000** [comment]
Will merge when i've fixed the new bugs. Don't want to destabilize the stable git build yet.

**Comment by nichlas0010** [comment]
IT'S NOT EVEN MAPMERGED WTF

**Pull request merged**
