### PR TITLE
Skills implementation

### PR DESCRIPTION
**Pull request by Cdey78**
Adds skills to the game, defining what your character is "mentally" capable of, such as knowing how to commit surgery without killing the poor guy.

TODO:
[./] - Implement the ENGINEERING skill. (Somewhat done, I can't really add it to EVERYTHING. Reserved for future stuff like the warp core, and other ship-related systems. Does affect construction with sheets, however.
[./] - Implement the MEDICAL skill.
[./] - Implement the PILOTING skill.
[n/a] - Implement the MELEE skill. -- Reserved for combat rework
[n/a] - Implement the RANGED skill. -- Reserved for combat rework
[n/a] - Implement (MORE?) skill(s).
--
The MEDICAL skill defines how capable you are at applying bruise packs, gauze, ointment, and your ability to do surgery properly. Does not affect medical scanners.
--
The PILOTING skill determines if you are able to fly a starship or not. Lower skills means smaller vessels only.
--
The ENGINEERING skill determines if you can maintain, repair, and modify starship equipment. also, defines if you can build things with materials. Do note that this one is forever WIP, since it's too broad a category to cover all in one PR.
--
The MELEE. and RANGED skills are saved for a separate PR that will work on combat.
--
:cl: Cdey
balance: SKILLS!
balance: It is worth noting that this is more or less framework, and is continually going to be in-development.
add: Medical skill: No longer Is everyone masters of the future medicine! People like assistants and engineers won't be able to attempt medical practices effectively anymore.
add: Piloting skill: Ships of varying sizes are definitely hard to master.
add: Engineering skill: Oh lord, the warp core is going to explode! WHY DID THE ENGINEERS HAVE TO DIE?! Do note that this one is more WIP than others, but this basically should only affect sheet construction and ship systems at the moment.
/:cl: 

[why]: # Jobs are now even more of a requirement, and less of just access definitions.

### CODE REVIEW

**Comment by Kmc2000** [comment]
Neat stuff. 
Poke me when you want this merging.

**Comment by Super3222** [comment]
Cool stuff.

**Comment by Harcourt1** [comment]
I like it, no real suggestions but maybe add strength skill.

**Comment by Cdey78** [comment]
>Strength skill
Interbay had stats intertwined with the skill system, but I gutted it because I thought Kmc didn't want it.

**Comment by Cdey78** [comment]
That should be the last of it.

**Comment by Kmc2000** [comment]
Let's see what travis has to say now.

**Comment by Kmc2000** [comment]
Re-pull your branch. That'll fix the travis issues.

**Comment by Kmc2000** [comment]
What could possibly go wrong

**Pull request merged**
